import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Border from "@/components/ui/Border/Border";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "layout")}>
        <div className="flex justify-between absolute top-0 left-0 right-0">
          <div>turkishairlines.com</div>
          <div>searchfFlight Challenge</div>
        </div>
        <div className="absolute top-6 z-10 left-0 right-0">
          <Border />
        </div>
        {children}
      </body>
    </html>
  );
}
